source 'http://rubygems.org'

gem 'rails', '3.0.4'
gem "mysql2"
gem "haml"
gem "haml-rails"
gem "formtastic"
gem "jquery-rails"
gem "mysql", "2.8.1"     
gem "capistrano"
gem "capistrano-ext"
gem "yard"
gem "rdoc"
gem "ci_reporter"
gem "rspec"
gem "rspec-rails"
gem "mechanize"

# Bundle gems for the local environment. Make sure to
# put test-only gems in this group so their generators
# and rake tasks are available in development mode:
group :development, :test do
  gem "ruby-debug"
  gem "factory_girl_rails"
  gem "webrat"
  gem "capybara"
  gem "database_cleaner"
  gem "cucumber-rails"
  gem "pickle"
  gem "rcov"     
  gem "gherkin"     
  gem "mechanize"     
  gem "shoulda"
  gem "machinist"     
  gem "random_data"
  gem "faker"
end

