# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{cucumber_off_rails}
  s.version = "0.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = [%q{Jeremiah Hemphill}]
  s.date = %q{2011-07-22}
  s.description = %q{Nondestructive cucumber testing without using the rails stack setup for Hudson/Jenkins integration}
  s.email = %q{jeremiah@cloudspace.com}
  s.executables = [%q{cucumber_off_rails}]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Changelog.markdown",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/cucumber_off_rails",
    "cucumber_off_rails.gemspec",
    "lib/cucumber_off_rails.rb",
    "lib/cucumber_off_rails/generator.rb",
    "lib/cucumber_off_rails/generator/application.rb",
    "lib/cucumber_off_rails/generator/options.rb",
    "lib/cucumber_off_rails/templates/Gemfile",
    "lib/cucumber_off_rails/templates/Rakefile",
    "lib/cucumber_off_rails/templates/features/.htaccess",
    "lib/cucumber_off_rails/templates/features/sample.feature",
    "lib/cucumber_off_rails/templates/features/step_definitions/debugging_steps.rb",
    "lib/cucumber_off_rails/templates/features/step_definitions/linking_steps.rb",
    "lib/cucumber_off_rails/templates/features/step_definitions/login_steps.rb",
    "lib/cucumber_off_rails/templates/features/step_definitions/selector_steps.rb",
    "lib/cucumber_off_rails/templates/features/step_definitions/validation_steps.rb",
    "lib/cucumber_off_rails/templates/features/support/env.rb",
    "lib/cucumber_off_rails/templates/features/support/hooks.rb",
    "lib/cucumber_off_rails/templates/features/support/paths.rb",
    "lib/cucumber_off_rails/templates/features/support/selectors.rb",
    "spec/cucumber_off_rails_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/jeremiahishere/cucumber_off_rails}
  s.licenses = [%q{MIT}]
  s.require_paths = [%q{lib}]
  s.rubygems_version = %q{1.8.5}
  s.summary = %q{Nondestructive Cucumber Testing}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.3"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<cucumber>, [">= 0"])
      s.add_development_dependency(%q<mechanize>, ["~> 1.0.0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<capybara>, ["~> 0.4.0"])
      s.add_development_dependency(%q<capybara-mechanize>, ["~> 0.2.7"])
    else
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.3"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<cucumber>, [">= 0"])
      s.add_dependency(%q<mechanize>, ["~> 1.0.0"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<capybara>, ["~> 0.4.0"])
      s.add_dependency(%q<capybara-mechanize>, ["~> 0.2.7"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.3"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<cucumber>, [">= 0"])
    s.add_dependency(%q<mechanize>, ["~> 1.0.0"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<capybara>, ["~> 0.4.0"])
    s.add_dependency(%q<capybara-mechanize>, ["~> 0.2.7"])
  end
end

