source 'http://rubygems.org'

gem 'rails', '3.1.4'

gem 'mysql2'
gem "devise"
gem "cancan"
gem "paperclip"
gem "trackable_tasks"
gem "capistrano"
gem "capistrano-ext"
gem 'ruby-debug19', :require => 'ruby-debug'
gem "formtastic"
gem "kaminari"
gem "therubyracer"
gem "haml-rails"
gem "haml"

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.1.5'
  gem 'coffee-rails', '~> 3.1.1'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer'

  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# Use unicorn as the web server
# gem 'unicorn'


group :test do
  # Pretty printed test output
  gem 'turn', '0.8.2', :require => false
end
